import { createSlice } from '@reduxjs/toolkit';

// Create the initial state
const initialState = {
  userId: null,
};

// Create a slice with the state and reducers
const counterSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    setUserId: (state, action) => {
      state.userId = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { setUserId } = counterSlice.actions;

// Export the reducer to be added to the store
export default counterSlice.reducer;
